# Config file for automatic testing at travis-ci.org.

language: python

python:
  - 3.4
  - 3.5
  - 3.6
  - 3.7-dev

install:
  - make

script:
  - source .venv/bin/activate && python test/test_ingde.py